### ISSUE TITLE
Build failure with GHC 9.12.2

### ISSUE THREAD

**Issue by sjakobi** [quchen/pgp-wordlist#5]
```
Building library for pgp-wordlist-0.1.0.3...
[1 of 6] Compiling Data.Text.PgpWordlist.Internal.AltList ( src/Data/Text/PgpWordlist/Internal/AltList.hs, dist/build/Data/Text/PgpWordlist/Internal/AltList.o, dist/build/Data/Text/PgpWordlist/Internal/AltList.dyn_o )
src/Data/Text/PgpWordlist/Internal/AltList.hs:87:10: error: [GHC-39999]
    • No instance for ‘Functor (AltList a)’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Bi.Bifunctor AltList’
   |
87 | instance Bi.Bifunctor AltList where
   |          ^^^^^^^^^^^^^^^^^^^^

[3 of 6] Compiling Data.Text.PgpWordlist.Internal.Word8Bimap ( src/Data/Text/PgpWordlist/Internal/Word8Bimap.hs, dist/build/Data/Text/PgpWordlist/Internal/Word8Bimap.o, dist/build/Data/Text/PgpWordlist/Internal/Word8Bimap.dyn_o )
Error: [Cabal-7125]
Failed to build pgp-wordlist-0.1.0.3. See the build log above for details.
```

**Comment by sjakobi** [comment]
Apparently GHC >= 9.6 is affected due to Functor becoming a superclass of Bifunctor in base-4.18.

I have revised v0.1.0.1..v0.1.0.3 on Hackage with bounds `base < 4.18`.

`prettyprinter`'s testsuite depends on `pgp-wordlist`. Not sure if we need a new release or whether we could remove this dependency.

**Comment by sjakobi** [comment]
v0.1 builds with GHC 9.12 and `--allow-newer="text,bytestring"`. Maybe we can revise its bounds and use it for  `prettyprinter`'s testsuite.

**Comment by sjakobi** [comment]
v0.1 seems to work for `prettyprinter`. I've revised it and removed the upper bounds for `text` and `bytestring`. If that ever causes problems, the bounds can be revised again. I hope that's alright with you, @quchen! :)
